package TSXProdMap;

our %subProdMap = (
	"TSX RIGHTS/WARRANTS"	=> [ "T_RW_RT" , "T_RW_RT_LL" , "T_RW_CPF_OPN" , "T_RW" , "T_RW_LL" ] ,
	"TSX NOTES/DEBENTURES"	=> [ "T_DEBT" , "T_DEBT_PS" , "T_DEBT_RT_PS" , "T_DEBT_RT_LL" , "T_DEBT_LL" ] ,
	"TSX EXCHANGEABLES"		=> [ "T_EXCH_RT" , "T_EXCH_RT_LL" , "T_EXCH" , "T_EXCH_LL" ] ,
	"TSX SETTLEMENT TERMS"	=> [ "T_ST" , "T_ST_LL" ] ,
	"TSX Special Crosses"	=> [ "T_SPC" ] ,
	"TSX HIGH CLOB"			=> [ "T_HI_CLOB_ETF" , "T_HI_CLOB_ETF_PS" , "T_HI_CLOB_ETF_LL" , "T_HI_CLOB_ETF_INTL" , 
								"T_HI_CLOB_ETF_INTL_PS", "T_HI_CLOB_ETF_INTL_LL" , "T_HI_CLOB_ETF_ICE" , "T_HI_CLOB_ETF_ICE_PS" , 
								"T_HI_CLOB_ETF_ICE_LL" , "T_HI_CLOB_ETF_ICE_INTL" , "T_HI_CLOB_ETF_ICE_INTL_PS" , 
								"T_HI_CLOB_ETF_ICE_INTL_LL" , "T_HI_CLOB_ETF_JIT" , "T_HI_CLOB_ETF_JIT_PS" , "T_HI_CLOB_ETF_JIT_LL" , 
								"T_HI_CLOB_ETF_JIT_INTL" , "T_HI_CLOB_ETF_JIT_INTL_PS" , "T_HI_CLOB_ETF_JIT_INTL_LL" , 
								"T_HI_CLOB" , "T_HI_CLOB_PS" , "T_HI_CLOB_LL" , "T_HI_CLOB_INTL" , "T_HI_CLOB_INTL_PS" , 
								"T_HI_CLOB_INTL_LL" , "T_HI_CLOB_ICE" , "T_HI_CLOB_ICE_PS" , "T_HI_CLOB_ICE_LL" , 
								"T_HI_CLOB_ICE_INTL" , "T_HI_CLOB_ICE_INTL_PS" , "T_HI_CLOB_ICE_INTL_LL" , 
								"T_HI_CLOB_JIT" , "T_HI_CLOB_JIT_PS" , "T_HI_CLOB_JIT_LL" , "T_HI_CLOB_JIT_INTL" , 
								"T_HI_CLOB_JIT_INTL_PS" , "T_HI_CLOB_JIT_INTL_LL" , 
								"T_HI_CLOB_CORR" ] ,
	"TSX LOW CLOB"			=> [ "T_LO_CLOB_T2_REG" , "T_LO_CLOB_T2_REG_PS" , "T_LO_CLOB_T2_REG_LL" , "T_LO_CLOB_ICE_T2" , 
								"T_LO_CLOB_ICE_T2_PS" , "T_LO_CLOB_ICE_T2_LL" , "T_LO_CLOB_JITNEY_T2" , "T_LO_CLOB_JITNEY_T2_PS" , 
								"T_LO_CLOB_JITNEY_T2_LL" , "T_LO_CLOB_T1_REG" , "T_LO_CLOB_T1_REG_PS" , "T_LO_CLOB_T1_REG_LL" , 
								"T_LO_CLOB_ICE_T1" , "T_LO_CLOB_ICE_T1_PS" , "T_LO_CLOB_ICE_T1_LL" , "T_LO_CLOB_JITNEY_T1" , 
								"T_LO_CLOB_JITNEY_T1_PS" , "T_LO_CLOB_JITNEY_T1_LL" , 
								"T_LO_CLOB_CORR" ] ,
	"TSX MBF Trading"		=> [ "T_MBF" ] ,
	"TSX MOC"				=> [ "T_MOC" , "T_HI_MOC" , "T_LO_MOC" ] ,
	"TSX EXTENDED TRADING"	=> [ "T_EXT_CORR" , "T_EXT" ] ,
	
#	Note - on invoices and in POFEERECONSUM, TSX RT Trading incorporates both Equity and ETF RT subproducts.
#	--------------------------------------------------------------------------------------------------------
	"TSX RT Trading"		=> [ "T_RT_CORR" , 
								"T_HI_RT" , "T_HI_RT_PART" , "T_HI_RT_MGF" , 
								"T_HI_RT_PS" , "T_HI_RT_LL" , 
								"T_HI_RT_INTL" , "T_HI_RT_PART_INTL" , "T_HI_RT_MGF_INTL" , 
								"T_HI_RT_INTL_PS" , "T_HI_RT_INTL_LL" , 
								"T_LO_RT" ,	"T_LO_RT_PART" , "T_LO_RT_MGF" , 
								"T_LO_RT_PS" , "T_LO_RT_LL" , 
								"T_HI_RT_OL" , "T_LO_RT_OL" ,
								"T_HI_MOO_RT" , "T_LO_MOO_RT" ,
								"T_HI_MOC_RT" , "T_LO_MOC_RT" ,
								"T_HI_ETF_RT" , "T_HI_ETF_RT_PART" , "T_HI_ETF_RT_MGF" , 
								"T_HI_ETF_RT_PS" , "T_HI_ETF_RT_LL" , 
								"T_HI_ETF_RT_INTL" , "T_HI_ETF_RT_PART_INTL" , "T_HI_ETF_RT_MGF_INTL" , 
								"T_HI_ETF_RT_INTL_PS" , "T_HI_ETF_RT_INTL_LL" , 
								"T_LO_ETF_RT" , "T_LO_ETF_RT_PART" , "T_LO_ETF_RT_MGF" , 
								"T_LO_ETF_RT_PS" , "T_LO_ETF_RT_LL" , 
								"T_HI_ETF_RT_OL" , "T_LO_ETF_RT_OL" , 
								"T_HI_ETF_MOC_RT" , "T_LO_ETF_MOC_RT" ] ,
#	"TSX ETF RT Trading"	=> [ "T_HI_ETF_RT" , "T_HI_ETF_RT_PART" , "T_HI_ETF_RT_MGF" , 
#								"T_HI_ETF_RT_PS" , "T_HI_ETF_RT_LL" , 
#								"T_HI_ETF_RT_INTL" , "T_HI_ETF_RT_PART_INTL" , "T_HI_ETF_RT_MGF_INTL" , 
#								"T_HI_ETF_RT_INTL_PS" , "T_HI_ETF_RT_INTL_LL" , 
#								"T_LO_ETF_RT" , "T_LO_ETF_RT_PART" , "T_LO_ETF_RT_MGF" , 
#								"T_LO_ETF_RT_PS" , "T_LO_ETF_RT_LL" , 
#								"T_HI_ETF_RT_OL" , "T_LO_ETF_RT_OL" , 
#								"T_HI_ETF_MOC_RT" , "T_LO_ETF_MOC_RT" ] ,
	"TSX OPENING AUCTION"	=> [ "T_MOO_RT" , "T_MOO_CORR" , "T_MOO" , "T_HI_MOO" , "T_LO_MOO" ] ,
	"TSX Cross Printing"	=> [ "T_CPF" ] ,
	"TSX MGF Trading"		=> [ "T_HI_OL" , "T_HI_MGF" , "T_HI_MGF_INTL" , "T_LO_OL" , "T_LO_MGF" , 
								"T_HI_MGF_CORR" , "T_LO_MGF_CORR" , "T_HI_MOC_AUTOFILL" , "T_LO_MOC_AUTOFILL" ] ,
	"TSX High Dark"			=> [ "T_HI_DARK_DARK" , "T_HI_DARK_DARK_INTL" ,
								"T_HI_SDL_DARK" , "T_HI_SDL_DARK_INTL" ,
								"T_HI_PEG_IOC_DARK" , "T_HI_PEG_IOC_DARK_INTL" ,
								"T_HI_LIT_DARK" , "T_HI_LIT_DARK_INTL" ,
								"T_HI_DARK_LIT" , "T_HI_DARK_LIT_INTL" ,
								"T_HI_DARK_DARK_ETF" , "T_HI_DARK_DARK_ETF_INTL" ,
								"T_HI_SDL_DARK_ETF" , "T_HI_SDL_DARK_ETF_INTL" ,
								"T_HI_PEG_IOC_DARK_ETF" , "T_HI_PEG_IOC_DARK_ETF_INTL" ,
								"T_HI_LIT_DARK_ETF" , "T_HI_LIT_DARK_ETF_INTL" ,
								"T_HI_DARK_LIT_ETF" , "T_HI_DARK_LIT_ETF_INTL" ,
								"T_HI_CMO" , "T_HI_CMO_INTL" , "T_HI_CMO_UNINT_CROSS" , "T_HI_CMO_UNINT_CROSS_INTL" ,
								"T_HI_ETF_CMO" , "T_HI_ETF_CMO_UNINT_CROSS" ] ,
	"TSX Low Dark"			=> [ "T_LO_DARK_DARK_T2" , "T_LO_LIT_DARK_T2" , "T_LO_DARK_LIT_T2" ,
								"T_LO_SDL_DARK_T2" , "T_LO_PEG_IOC_DARK_T2" , 
								"T_LO_DARK_DARK_T1" , "T_LO_LIT_DARK_T1" , "T_LO_DARK_LIT_T1" , 
								"T_LO_SDL_DARK_T1" , "T_LO_PEG_IOC_DARK_T1" ,
								"T_LO_CMO" , "T_LO_CMO_UNINT_CROSS" ] ,
	"NEX TRADING"			=> [ "NEX" , "NEX_PS" , "NEX_LL" , "NEX_VOD" , "NEX_VOD_PS" , "NEX_VOD_LL" ] ,
	"TSXV HIGH CLOB"		=> [ "V_HI_CLOB" , "V_HI_CLOB_PS" , "V_HI_CLOB_LL" , "V_HI_CLOB_ICE" , "V_HI_CLOB_ICE_PS" , 
								"V_HI_CLOB_ICE_LL" , "V_HI_CLOB_JIT" , "V_HI_CLOB_JIT_PS" , "V_HI_CLOB_JIT_LL" , 
								"V_HI_CLOB_CORR" , 
								"V_HI_DEBT" , "V_HI_DEBT_PS" , "V_HI_DEBT_LL" , "V_HI_DEBT_JIT" , "V_HI_DEBT_JIT_PS" , 
								"V_HI_DEBT_JIT_LL" , "V_HI_DEBT_ICE" , "V_HI_DEBT_ICE_PS" , "V_HI_DEBT_ICE_LL" ] ,
	"TSXV LOW CLOB"			=> [ "V_LO_CLOB_T2_REG" , "V_LO_CLOB_T2_REG_PS" , "V_LO_CLOB_T2_REG_LL" , "V_LO_CLOB_ICE_T2" , 
								"V_LO_CLOB_ICE_T2_PS" , "V_LO_CLOB_ICE_T2_LL" , "V_LO_CLOB_JIT_T2" , "V_LO_CLOB_JIT_T2_PS" , 
								"V_LO_CLOB_JIT_T2_LL" , "V_LO_CLOB_T1_REG" , "V_LO_CLOB_T1_REG_PS" , "V_LO_CLOB_T1_REG_LL" , 
								"V_LO_CLOB_ICE_T1" , "V_LO_CLOB_ICE_T1_PS" , "V_LO_CLOB_ICE_T1_LL" , "V_LO_CLOB_JIT_T1" , 
								"V_LO_CLOB_JIT_T1_PS" , "V_LO_CLOB_JIT_T1_LL" , 
								"V_LO_CLOB_CORR" , 
								"V_LO_DEBT_T2" , "V_LO_DEBT_T2_PS" , "V_LO_DEBT_T2_LL" , "V_LO_DEBT_JIT_T2" , 
								"V_LO_DEBT_JIT_T2_PS" , "V_LO_DEBT_JIT_T2_LL" , "V_LO_DEBT_ICE_T2" , "V_LO_DEBT_ICE_T2_PS" , 
								"V_LO_DEBT_ICE_T2_LL" , "V_LO_DEBT_T1" , "V_LO_DEBT_T1_PS" , "V_LO_DEBT_T1_LL" , 
								"V_LO_DEBT_JIT_T1" , "V_LO_DEBT_JIT_T1_PS" , "V_LO_DEBT_JIT_T1_LL" , "V_LO_DEBT_ICE_T1" , 
								"V_LO_DEBT_ICE_T1_PS" , "V_LO_DEBT_ICE_T1_LL" , 
								"V_LO_DEBT_CORR" ] ,
	"TSXV Special Crosses"	=> [ "V_SPC" , 	"V_SPC_DEBT" ] ,
	"TSXV OPENING AUCTION"	=> [ "V_MOO" , "V_HI_MOO" , "V_LO_MOO" , "V_MOO_CORR" , 
								"V_MOO_DEBT" , "V_HI_MOO_DEBT" , "V_LO_MOO_DEBT" , "V_MOO_DEBT_CORR" ] ,
	"TSXV Cross Printing"	=> [ "V_CPF" , 	"V_CPF_DEBT" ] ,
	"TSXV VOD Trading"		=> [ "V_HI_VOD" , "V_HI_VOD_PS" , "V_HI_VOD_LL" , "V_LO_VOD" , "V_LO_VOD_PS" , "V_LO_VOD_LL" , 
								"V_HI_VOD_OL_AUTOFILL" , "V_LO_VOD_OL_AUTOFILL" , "V_HI_MOC_VOD" , "V_LO_MOC_VOD" ] ,
	"TSXV Oddlot Autofill"	=> [ "V_HI_OL_AUTOFILL" , "V_LO_T1_OL_AUTOFILL" , "V_LO_T2_OL_AUTOFILL" , 
								"V_HI_MOC_AUTOFILL" , "V_LO_T1_MOC_AUTOFILL" , "V_LO_T2_MOC_AUTOFILL" ] ,
	"TSXV High Dark"		=> [ "V_HI_DARK_DARK" , "V_HI_LIT_DARK" , "V_HI_DARK_LIT" ,
								"V_HI_SDL_DARK" , "V_HI_PEG_IOC_DARK" ,
								"V_HI_CMO" , "V_HI_CMO_UNINT_CROSS" ] ,
	"TSXV Low Dark"			=> [ "V_LO_DARK_DARK_T2" , "V_LO_LIT_DARK_T2" , "V_LO_DARK_LIT_T2" , 
								"V_LO_SDL_DARK_T2" , "V_LO_PEG_IOC_DARK_T2" ,
								"V_LO_DARK_DARK_T1" , "V_LO_LIT_DARK_T1" , "V_LO_DARK_LIT_T1" ,
								"V_LO_SDL_DARK_T1" , "V_LO_PEG_IOC_DARK_T1" ,
								"V_LO_CMO" , "V_LO_CMO_UNINT_CROSS" ] ,
	"TSXV MOC"				=> [ "V_MOC" , "V_HI_MOC" , "V_LO_MOC" ] ,
	"TSXV EXTENDED TRADING"	=> [ "V_EXT" , 	"V_EXT_CORR" ] ,	
	"ELP Rebate"			=> [ "T_HI_ELP" , "T_HI_ELP_ETF" ]
);

our %intToExtProdMap = (
	"TSX OPENING AUCTION"		=> "TSX Opening Auction" ,
	"TSXV OPENING AUCTION"		=> "TSX Venture Opening Auction" ,
	"TSX MBF Trading"			=> "MBF" ,
	"TSX HIGH CLOB"				=> "TSX High CLOB" ,
	"TSXV HIGH CLOB"			=> "TSX Venture High CLOB" ,
	"TSX LOW CLOB"				=> "TSX Low CLOB" ,
	"TSXV LOW CLOB"				=> "TSX Venture Low CLOB" ,
	"TSX MOC"					=> "TSX MOC" ,
	"TSXV MOC"					=> "TSXV MOC" ,
	"TSX High Dark"				=> "TSX High Dark" ,
	"TSX Low Dark"				=> "TSX Low Dark" ,
	"TSXV High Dark"			=> "TSXV High Dark" ,
	"TSXV Low Dark"				=> "TSXV Low Dark" ,
	"TSX EXTENDED TRADING"		=> "TSX Extended Trading" ,
	"TSXV EXTENDED TRADING"		=> "TSXV Extended Trading" ,
	"TSX SETTLEMENT TERMS"		=> "Settlement Terms" ,
	"TSX RIGHTS/WARRANTS"		=> "TSX Rights/Warrants" ,
	"TSX NOTES/DEBENTURES"		=> "TSX Notes/Debentures" ,
	"TSX EXCHANGEABLES"			=> "TSX Exchangeables" ,
	"TSX RT Trading"			=> "TSX RT" ,
	"TSX ETF RT Trading"		=> "TSX ETF RT" ,
	"TSXV VOD Trading"			=> "TSXV VOD" ,
	"NEX TRADING"				=> "NEX Trading" ,
	"TSX MGF Trading"			=> "TSX MGF Autofill" ,
	"TSXV Oddlot Autofill"		=> "TSXV Oddlot Autofill" ,
	"ELP Rebate"				=> "ELP Rebate"
);

1;
